services:
  adsai_pong:
    build: .
    image: adsai_pong:latest
    container_name: adsai_pong
    restart: on-failure
    ports:
      - "8501:8501"

    volumes:
      - "./webapp/db:/app/webapp/db"
      - "./webapp/model/results:/app/webapp/model/results"

